<?php
/**
 * Plugin Mobile for Roundcube
 * @author Sergio Loyola
 * @license GNU GPLv3+
 *
 */

$labels = array();
$labels['mobile'] = 'Vista móvil';
$labels['desktop'] = 'Vista de escritorio';
$labels['pull_to_refresh'] = 'Click para actualizar';
$labels['release_to_refresh'] = 'Libere para actualizar';
$labels['slide to delete message'] = 'Deslice para eliminar el mensaje';
$labels['release to delete message'] = 'Liberar para eliminar mensaje';
$labels['slide to mark as read'] = 'Deslice para marcar como leido';
$labels['release to mark as read'] = 'Libere para marcar como leido';
$labels['slide to mark as unread'] = 'Deslice para marcar como no leido';
$labels['release to mark as unread'] = 'Libere para marcar como no leido';
